-- What a member — or a claimant — is told at every stage of an exit
-- (S-1705, CLS-US-007, RES-US-007, DEM-US-008, FRD 11.1).
--
-- One event per stage per kind of request: closure.*, resignation.* and
-- demised.* for submitted, under_review, approved (with the payout) and
-- rejected (with the reason), each an email and a WhatsApp template the
-- Society edits at Configuration -> Notification wording. A closure or a
-- resignation writes to the member; a claim writes to the claimant, whose
-- contact is on the claim (src/lib/ledger/exit-notifications.ts).
set local albarakah.actor_description = 'migration 0080_exit_notifications';

insert into notification_template
    (event_code, channel, subject, body, description)
values
    ('closure.submitted', 'email',
     'Al Barakah: your account closure request {{reference}} received',
     E'Assalamoualaikoum {{recipient_name}},\n\nWe have received your account closure request ({{reference}}). It will be reviewed and we will write to you when it is decided.\n\nAl Barakah MCSL',
     'Sent when an account closure request is submitted.'),
    ('closure.submitted', 'whatsapp', null,
     'Assalamoualaikoum {{recipient_name}}, Al Barakah has received your account closure request ({{reference}}). We will write to you when it is decided.',
     'Sent when an account closure request is submitted.'),
    ('closure.under_review', 'email',
     'Al Barakah: your account closure request {{reference}} is under review',
     E'Assalamoualaikoum {{recipient_name}},\n\nYour account closure request ({{reference}}) is now under review. {{comment}}\n\nAl Barakah MCSL',
     'Sent when a reviewer forwards it to the next step.'),
    ('closure.under_review', 'whatsapp', null,
     'Assalamoualaikoum {{recipient_name}}, your account closure request ({{reference}}) is under review at Al Barakah. {{comment}}',
     'Sent when a reviewer forwards it to the next step.'),
    ('closure.approved', 'email',
     'Al Barakah: your account closure request {{reference}} paid out',
     E'Assalamoualaikoum {{recipient_name}},\n\nYour account closure request ({{reference}}) has been approved and Rs {{amount}} has been paid out by {{method}} — receipt {{receipt_no}}. The account is now closed.\n\nAl Barakah MCSL',
     'Sent when it is approved and paid out.'),
    ('closure.approved', 'whatsapp', null,
     'Assalamoualaikoum {{recipient_name}}, your account closure request ({{reference}}) is approved: Rs {{amount}} paid out by {{method}}, receipt {{receipt_no}}. Al Barakah MCSL',
     'Sent when it is approved and paid out.'),
    ('closure.rejected', 'email',
     'Al Barakah: your account closure request {{reference}} not approved',
     E'Assalamoualaikoum {{recipient_name}},\n\nYour account closure request ({{reference}}) was not approved. {{comment}}\n\nAl Barakah MCSL',
     'Sent when it is rejected, with the reason.'),
    ('closure.rejected', 'whatsapp', null,
     'Assalamoualaikoum {{recipient_name}}, your account closure request ({{reference}}) was not approved by Al Barakah. {{comment}}',
     'Sent when it is rejected, with the reason.'),
    ('resignation.submitted', 'email',
     'Al Barakah: your resignation {{reference}} received',
     E'Assalamoualaikoum {{recipient_name}},\n\nWe have received your resignation ({{reference}}). It will be reviewed and we will write to you when it is decided.\n\nAl Barakah MCSL',
     'Sent when a resignation is submitted.'),
    ('resignation.submitted', 'whatsapp', null,
     'Assalamoualaikoum {{recipient_name}}, Al Barakah has received your resignation ({{reference}}). We will write to you when it is decided.',
     'Sent when a resignation is submitted.'),
    ('resignation.under_review', 'email',
     'Al Barakah: your resignation {{reference}} is under review',
     E'Assalamoualaikoum {{recipient_name}},\n\nYour resignation ({{reference}}) is now under review. {{comment}}\n\nAl Barakah MCSL',
     'Sent when a reviewer forwards it to the next step.'),
    ('resignation.under_review', 'whatsapp', null,
     'Assalamoualaikoum {{recipient_name}}, your resignation ({{reference}}) is under review at Al Barakah. {{comment}}',
     'Sent when a reviewer forwards it to the next step.'),
    ('resignation.approved', 'email',
     'Al Barakah: your resignation {{reference}} paid out',
     E'Assalamoualaikoum {{recipient_name}},\n\nYour resignation ({{reference}}) has been approved and Rs {{amount}} has been paid out by {{method}} — receipt {{receipt_no}}. Your Shares and MSA are now closed.\n\nAl Barakah MCSL',
     'Sent when it is approved and paid out.'),
    ('resignation.approved', 'whatsapp', null,
     'Assalamoualaikoum {{recipient_name}}, your resignation ({{reference}}) is approved: Rs {{amount}} paid out by {{method}}, receipt {{receipt_no}}. Al Barakah MCSL',
     'Sent when it is approved and paid out.'),
    ('resignation.rejected', 'email',
     'Al Barakah: your resignation {{reference}} not approved',
     E'Assalamoualaikoum {{recipient_name}},\n\nYour resignation ({{reference}}) was not approved. {{comment}}\n\nAl Barakah MCSL',
     'Sent when it is rejected, with the reason.'),
    ('resignation.rejected', 'whatsapp', null,
     'Assalamoualaikoum {{recipient_name}}, your resignation ({{reference}}) was not approved by Al Barakah. {{comment}}',
     'Sent when it is rejected, with the reason.'),
    ('demised.submitted', 'email',
     'Al Barakah: the claim {{reference}} received',
     E'Assalamoualaikoum {{recipient_name}},\n\nWe have received the claim for {{member_name}} ({{reference}}). It will be reviewed and we will write to you when it is decided.\n\nAl Barakah MCSL',
     'Sent when a claim is submitted.'),
    ('demised.submitted', 'whatsapp', null,
     'Assalamoualaikoum {{recipient_name}}, Al Barakah has received the claim for {{member_name}} ({{reference}}). We will write to you when it is decided.',
     'Sent when a claim is submitted.'),
    ('demised.under_review', 'email',
     'Al Barakah: the claim {{reference}} is under review',
     E'Assalamoualaikoum {{recipient_name}},\n\nThe claim for {{member_name}} ({{reference}}) is now under review. {{comment}}\n\nAl Barakah MCSL',
     'Sent when a reviewer forwards it to the next step.'),
    ('demised.under_review', 'whatsapp', null,
     'Assalamoualaikoum {{recipient_name}}, the claim for {{member_name}} ({{reference}}) is under review at Al Barakah. {{comment}}',
     'Sent when a reviewer forwards it to the next step.'),
    ('demised.approved', 'email',
     'Al Barakah: the claim {{reference}} paid out',
     E'Assalamoualaikoum {{recipient_name}},\n\nThe claim for {{member_name}} ({{reference}}) has been approved and Rs {{amount}} has been paid out by {{method}} — receipt {{receipt_no}}. The accounts are now closed.\n\nAl Barakah MCSL',
     'Sent when it is approved and paid out.'),
    ('demised.approved', 'whatsapp', null,
     'Assalamoualaikoum {{recipient_name}}, the claim for {{member_name}} ({{reference}}) is approved: Rs {{amount}} paid out by {{method}}, receipt {{receipt_no}}. Al Barakah MCSL',
     'Sent when it is approved and paid out.'),
    ('demised.rejected', 'email',
     'Al Barakah: the claim {{reference}} not approved',
     E'Assalamoualaikoum {{recipient_name}},\n\nThe claim for {{member_name}} ({{reference}}) was not approved. {{comment}}\n\nAl Barakah MCSL',
     'Sent when it is rejected, with the reason.'),
    ('demised.rejected', 'whatsapp', null,
     'Assalamoualaikoum {{recipient_name}}, the claim for {{member_name}} ({{reference}}) was not approved by Al Barakah. {{comment}}',
     'Sent when it is rejected, with the reason.')
on conflict (event_code, channel) do nothing;
